global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'polkadot-processor'
    static_configs:
      - targets: ['processor-polkadot:3000']
  
  - job_name: 'assethub-processor'
    static_configs:
      - targets: ['processor-assethub:3001']
