apiVersion: 1

contactPoints:
  - orgId: 1
    name: Email
    receivers:
      - uid: email-receiver
        type: email
        settings:
          addresses: "${ALERT_EMAIL_1};${ALERT_EMAIL_2}"
          singleEmail: true
        disableResolveMessage: false
