export * as balances from './balances/storage'
export * as democracy from './democracy/storage'
export * as council from './council/storage'
export * as technicalCommittee from './technical-committee/storage'
export * as treasury from './treasury/storage'
export * as preimage from './preimage/storage'
export * as communityCouncil from './community-council/storage'
export * as communityTreasury from './community-treasury/storage'
