export {handleConvictionVote} from '@assethub/mappings/referendumV2/extrinsics/convictionVoting'
export {handleDelegate} from '@assethub/mappings/referendumV2/extrinsics/delegate'
export {handleUndelegate} from '@assethub/mappings/referendumV2/extrinsics/undelegate'
export {handleRemoveVote} from '@assethub/mappings/referendumV2/extrinsics/removeVote'
export {handleRemoveOtherVote} from '@assethub/mappings/referendumV2/extrinsics/removeOtherVote'