export {handleSubmitted} from '@polkadot/mappings/referendumV2/events/referendaSubmitted'
export {handleApproved} from '@polkadot/mappings/referendumV2/events/referendaApproved'
export {handleKilled} from '@polkadot/mappings/referendumV2/events/referendaKilled'
export {handleConfirmStarted} from '@polkadot/mappings/referendumV2/events/referendaConfirmStarted'
export {handleCancelled} from '@polkadot/mappings/referendumV2/events/referendaCancelled'
export {handleDecisionStarted} from '@polkadot/mappings/referendumV2/events/referendaDecisionStarted'
export {handleDecisionDepositPlaced} from '@polkadot/mappings/referendumV2/events/referendaDecisionDepositPlaced'
export {handleConfirmAborted} from '@polkadot/mappings/referendumV2/events/referendaConfirmAborted'
export {handleTimedOut} from '@polkadot/mappings/referendumV2/events/referendaTimedOut'
export {handleConfirmed} from '@polkadot/mappings/referendumV2/events/referendaConfirmed'
export {handleRejected} from '@polkadot/mappings/referendumV2/events/referendaRejected'
// export {handleReferendumV2ExecutionSchedule} from './referendaExecution'
export {handleReferendumV2Execution} from '@polkadot/mappings/referendumV2/events/referendaExecution'
export {handleMetadataSet, handleMetadataCleared} from '@polkadot/mappings/referendumV2/events/referendaMetadata'
